

services:
  web:
    build: ./zenviabnb_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./zenviabnb_backend/:/usr/src/zenviabnb_backend/
    ports:
      - "8000:8000"
    env_file:
      - .env.dev 
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgreuser
      - POSTGRES_PASSWORD=postgrepassword
      - POSTGRES_DB=zenviabnb

volumes:
  postgres_data:
    